<Project>
  <PropertyGroup>
    <VersionPrefix>0.0.2</VersionPrefix>
    <VersionSuffix>beta.1</VersionSuffix>
    <Product>SadPSX</Product>
    <Authors>kadu04t</Authors>
    <Copyright>Copyright (c) 2026 kadu04t</Copyright>
    <RepositoryUrl>https://github.com/kadu04t/SadPSX</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
  </PropertyGroup>
</Project>
